### ISSUE TITLE
Enabling branch protections?

### ISSUE THREAD

**Issue by springmeyer** [maplibre/maplibre-tile-spec#61]
@mactrem @nyurik @ebrelsford - now that all tests on CI are passing after (https://github.com/maplibre/maplibre-tile-spec/pull/56), how about we enable branch protections to ensure:

 - CI must pass for PRs to merge
 - PRs must have a review before merging

<img width="940" alt="Screenshot 2024-05-30 at 4 35 44 PM" src="https://github.com/maplibre/maplibre-tile-spec/assets/20300/3645a3f8-9ab3-404e-8ebd-a236d7a4f136">

Note: I'm mostly proposing that this is possible. It would be reasonable to delay a little longer on this formality until more refactoring is done. What do folks think?

**Comment by mactrem** [comment]
Yes, we should definitely add branch protection. Even if i'm still in a major refactoring phase, from now on only changes should be merged when the CI passes

**Comment by nyurik** [comment]
Agree! Unfortunately GitHub CI requires an explicit list of CI jobs to pass. In [Martin](https://github.com/maplibre/martin/blob/main/.github/workflows/ci.yml#L691C1-L699C45), I have used this "final job" so that the list of explicit passed job can be managed in the repo:

```yml
  # This final step is needed to mark the whole workflow as successful
  # Don't change its name - it is used by the merge protection rules
  done:
    name: CI Finished
    runs-on: ubuntu-latest
    needs: [ ... ]  # This is the list of all the other jobs that must pass for this job to start
    steps:
      - name: Finished
        run: echo "CI finished successfully"
```
